### ISSUE TITLE
php composer.phar require belousovr/belousovChatBundle

### ISSUE THREAD

**Issue by ElarbiMohamedAymen** [romanandreyvich/belousovChatBudle#1]
i got this error "  [InvalidArgumentException]                                                                                           
  Could not find package belousovr/belousovChatBundle at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability        " 

when i run this command 
"php composer.phar require belousovr/belousovChatBundle" how can i fix it ?

**Comment by romanandreyvich** [comment]
Hi, u need to set minimum-stability: "dev" in your composer.json

Belousov Roman

**Comment by ElarbiMohamedAymen** [comment]
can you please tell me how to do that ? i will be greatfull

2016-11-26 16:07 GMT+01:00 Roman Belousov <notifications@github.com>:
